export default {
  POST_LIST_GET_ATTEMPT: 'POST_LIST_GET_ATTEMPT',
  POST_LIST_GET_SUCCESS: 'POST_LIST_GET_SUCCESS',
  POST_LIST_GET_FAILURE: 'POST_LIST_GET_FAILURE',

  POST_DETAIL_GET_ATTEMPT: 'POST_DETAIL_GET_ATTEMPT',
  POST_DETAIL_GET_SUCCESS: 'POST_DETAIL_GET_SUCCESS',
  POST_DETAIL_GET_FAILURE: 'POST_DETAIL_GET_FAILURE',

  POST_COMMENT_GET_ATTEMPT: 'POST_COMMENT_GET_ATTEMPT',
  POST_COMMENT_GET_SUCCESS: 'POST_COMMENT_GET_SUCCESS',
  POST_COMMENT_GET_FAILURE: 'POST_COMMENT_GET_FAILURE',
};
